// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testprotobuf01.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// enum 为关键字， 作用为 定义一种枚举类型
type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_689ee709fcfb8402, []int{0}
}

// message为关键字 作用为定义一种消息类型
type Person struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32          `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Emails               []string       `protobuf:"bytes,3,rep,name=emails,proto3" json:"emails,omitempty"`
	Phones               []*PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_689ee709fcfb8402, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

// message 为关键字 作用为定义一种消息类型 可以被另外的消息类型嵌套使用
type PhoneNumber struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_689ee709fcfb8402, []int{1}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

func init() {
	proto.RegisterEnum("pb.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*Person)(nil), "pb.Person")
	proto.RegisterType((*PhoneNumber)(nil), "pb.PhoneNumber")
}

func init() { proto.RegisterFile("testprotobuf01.proto", fileDescriptor_689ee709fcfb8402) }

var fileDescriptor_689ee709fcfb8402 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0x0f, 0x83, 0x3b, 0x45, 0x5d, 0x06, 0x91, 0x1c, 0x63, 0x2f, 0x06, 0x85, 0x45,
	0xeb, 0x3f, 0x10, 0x0a, 0x15, 0xad, 0x5b, 0x82, 0xe0, 0x79, 0x03, 0xe3, 0x07, 0xb8, 0x49, 0xd8,
	0xa4, 0x87, 0xfe, 0x7b, 0x49, 0x0c, 0x8b, 0xb7, 0x67, 0x9e, 0x17, 0xde, 0x97, 0x81, 0x8b, 0x40,
	0x3e, 0xb8, 0xc9, 0x06, 0xab, 0xf7, 0x1f, 0x77, 0xf7, 0x5d, 0x42, 0x2c, 0x9d, 0x5e, 0x5a, 0x60,
	0x3b, 0x9a, 0xbc, 0x35, 0x88, 0x50, 0x9b, 0x61, 0x24, 0x5e, 0x88, 0x42, 0x36, 0x2a, 0x31, 0xb6,
	0x50, 0x0d, 0x9f, 0xc4, 0x4b, 0x51, 0xc8, 0x63, 0x15, 0x11, 0x2f, 0x81, 0xd1, 0x38, 0x7c, 0xff,
	0x78, 0x5e, 0x89, 0x4a, 0x36, 0x2a, 0x5f, 0x78, 0x0d, 0xcc, 0x7d, 0x59, 0x43, 0x9e, 0xd7, 0xa2,
	0x92, 0x8b, 0xd5, 0x79, 0xe7, 0x74, 0xb7, 0x8b, 0xe6, 0x75, 0x3f, 0x6a, 0x9a, 0x54, 0x8e, 0x97,
	0x1b, 0x58, 0xfc, 0xd3, 0xb1, 0xcf, 0x24, 0xca, 0xbb, 0xf9, 0xc2, 0x2b, 0xa8, 0xc3, 0xc1, 0xfd,
	0x4d, 0x9f, 0xad, 0x4e, 0xe7, 0xb6, 0xb7, 0x83, 0x23, 0x95, 0xa2, 0x9b, 0x5b, 0x68, 0x66, 0x85,
	0x00, 0x6c, 0xdb, 0x3f, 0x3e, 0xbd, 0xac, 0xdb, 0x23, 0x3c, 0x81, 0x7a, 0xd3, 0x6f, 0xd7, 0x6d,
	0x11, 0xe9, 0xbd, 0x57, 0xcf, 0x6d, 0xa9, 0x59, 0x7a, 0xf9, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xc5, 0x04, 0x2e, 0x49, 0x0a, 0x01, 0x00, 0x00,
}
